### ISSUE TITLE
Installing DataSHIELD packages fails

### ISSUE THREAD

**Issue by phildespres** [datashield/dsBase#210]
Hi,
I'm trying to install DataSHIELD through Opal web admin interface. The process seems to die silently. I see this in the logs:

ERROR org.obiba.opal.r.rserve.RserveService - DataShield packages properties extraction failed
org.obiba.opal.spi.r.RRuntimeException: Error in strsplit(pp, ",") : non-character argument

I can install/compile all DataSHIELD packages and dependencies through R. They appear in packages in the R administration page in Opal, but not in the DataSHIELD admin page. Packages are physically located in either /usr/lib64/R/library or /var/lib/rserver/R/library.

I'm on CentOS 7, using Opal 4.1.3.

Any clue?

**Comment by ymarcon** [comment]
Looks like you are using the legacy R server. I know where this piece of code is, I'll have a test and let you know.

**Comment by phildespres** [comment]
Using this, I do not see a more recent version?

Installed Packages
Name        : opal-rserver
Arch        : noarch
Version     : 1.4.3
Release     : 1
Size        : 0.0  
Repo        : installed
From repo   : bintray--obiba-rpm
Summary     : opal-rserver
License     : (c) null
Description :

**Comment by ymarcon** [comment]
The new R server is called Rock https://www.obiba.org/pages/news/release/rock/1.0/ but there is currently an issue when installing it on CentOS7. This will be fixed next week. Anyway Opal should be backward compatible.

**Comment by ymarcon** [comment]
I have just tested installing dsBase on the legacy R server and it works as expected.

You said you have other "DataSHIELD" packages. Which ones?

Also if some of these are installed in /usr/lib64/R/library they cannot be managed by the R server.

**Comment by phildespres** [comment]
If I use the "Install all DataSHIELD packages" from Opal, I confirm that a datashield folder is created in /var/lib/rserver/R/library. 
The web interface shows "No items" in the package list. Same if I try to install a specific package (e.g. dsBase); installs in /var/lib/rserver/R/library but doe nto show up in web interface...

Logs say:
Loading required package: unixtools
Error in strsplit(pp, ",") : non-character argument
Loading required package: unixtools
Loading required package: unixtools
Installing package into ‘/var/lib/rserver/R/library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.obiba.org/src/contrib/datashield_6.0.0.tar.gz'
Content type 'application/gzip' length 523 bytes
==================================================
downloaded 523 bytes

* installing *source* package ‘datashield’ ...
** using staged installation
** help
No man pages found in package  ‘datashield’ 
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (datashield)

The downloaded source packages are in
        ‘/tmp/Rtmp9jXnJ9/conn144728/downloaded_packages’
Loading required package: unixtools
Loading required package: unixtools
Error in strsplit(pp, ",") : non-character argument
Loading required package: unixtools
Loading required package: unixtools
Error in strsplit(pp, ",") : non-character argument
Loading required package: unixtools
Loading required package: unixtools
Error in strsplit(pp, ",") : non-character argument
Loading required package: unixtools

**Comment by ymarcon** [comment]
* Installing "datashield" will install only dsBase. Do you have other DS packages already installed ? (i.e from other sources)

* The error you have is when Opal extracts the DS configuration from the DESCRIPTION/DATASHIELD files of the installed pacakages:

```
dsFields <- c('AGGREGATE_METHODS', 'ASSIGN_METHODS, OPTIONS')

# extract DS fields from DESCRIPTION files
pkgs <- Map(function(p) {
  x <- as.list(p)
  x[names(x) %in% dsFields]
},
Filter(
  function(p)
    any(names(p) %in% dsFields),
  lapply(installed.packages()[, 1], function(p)
    as.data.frame(read.dcf(
      system.file('DESCRIPTION', package = p)
    )))
))
# extract DS fields from DATASHIELD files
x <- lapply(installed.packages()[, 1], function(p)
  system.file('DATASHIELD', package = p))
y <- lapply(x[lapply(x, nchar) > 0], function(f)
  as.list(as.data.frame(read.dcf(
    f
  ))))
# merge and prepare DS field values as arrays of strings
pkgs <- lapply(append(pkgs, y), function(p)
  lapply(p, function(pp)
    gsub('^\\s+|\\s+$', '', gsub('\n', '', unlist(strsplit(
      pp, ','
    ))))))
pkgs
``` 

Could you run (and debug) this code on the server?

**Comment by phildespres** [comment]
I installed manually packages and their deps listed here: https://github.com/obiba/cran/blob/gh-pages/src/contrib/PACKAGES
The y variables reads as: 

```> y
$resourcer
$resourcer$AssignMethods
                                                AssignMethods 
as.resource.data.frame,\nas.resource.object,\nas.resource.tbl 
Levels: as.resource.data.frame,\nas.resource.object,\nas.resource.tbl
```
and seems to lead to the strsplit error.

**Comment by ymarcon** [comment]
On my side I get for `y`:

```
$resourcer
$resourcer$AssignMethods
[1] "as.resource.data.frame,\nas.resource.object,\nas.resource.tbl"
```

**Comment by ymarcon** [comment]
Do you have R 3.x?

```
R.version
```

**Comment by phildespres** [comment]
```
R version 3.6.0 (2019-04-26) -- "Planting of a Tree"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-redhat-linux-gnu (64-bit)
```

**Comment by ymarcon** [comment]
That's the issue: since R 4.x the default stringsAsFactor is `FALSE` (finally!) but the script does not enforce the this parameter.

Corrected script is:

```
dsFields <- c('AggregateMethods', 'AssignMethods', 'Options')

# extract DS fields from DESCRIPTION files
pkgs <- Map(function(p) {
  x <- as.list(p)
  x[names(x) %in% dsFields]
},
Filter(
  function(p)
    any(names(p) %in% dsFields),
  lapply(installed.packages()[, 1], function(p)
    as.data.frame(read.dcf(system.file('DESCRIPTION', package = p)), stringsAsFactors = FALSE))
))
# extract DS fields from DATASHIELD files
x <- lapply(installed.packages()[, 1], function(p)
  system.file('DATASHIELD', package = p))
y <- lapply(x[lapply(x, nchar) > 0], function(f)
  as.list(as.data.frame(read.dcf(f), stringsAsFactors = FALSE)))
# merge and prepare DS field values as arrays of strings
pkgs <- lapply(append(pkgs, y), function(p)
  lapply(p, function(pp)
    gsub('^\\s+|\\s+$', '', gsub('\n', '', unlist(strsplit(
      pp, ','
    ))))))
pkgs
```

**Comment by ymarcon** [comment]
I will make a release of opal 4.1.5 and rock 1.0.4.

**Comment by phildespres** [comment]
Upgraded to R 4.1.0. Seems to work as expected so far. Thanks!
