### ISSUE TITLE
Is there a way to manually validate requests?

### ISSUE THREAD

**Issue by LaRiffle** [datashield/dsBase#278]
Hey, thanks a lot for the great work here!

I wonder if there is a way to set users that would have their requests manually validated by an administrator?

As far as I understand : I can allow a specific set of functions (should they be aggregations or not) for a user A and then A can run them as much as they want, possibly on the dataset or on a subset of the dataset. Is this correct?

Thanks a lot for your help!

**Comment by LaRiffle** [comment]
Ok very clear, so the analysis plan can then be packaged in a R script and for example added to a profile as a single allowed function.

Thanks @ymarcon for the quick response, I guess it's solved for me!

**Comment by StuartWheater** [comment]
One small clarification, the disclosure analysis not only depends on the method being called but also the state being analysed. A number of thresholds will be checked during the analysis (for example, a simple one is sample size), and if any checks are not passed no results will be returned (just a disclosure error).

**Comment by LaRiffle** [comment]
Yes this is very clear! but thanks again for clarifying :)
