### ISSUE TITLE
Subset with Columns and Complete Cases does not perform as expected because it performs a complete cases subset first. 

### ISSUE THREAD

**Issue by paulmorio** [datashield/dsBase#4]
Hello,

I am not sure if this is an intended pattern but its something I didn't expect. Also I don't know if the new release already addresses the issue but if it didn't I don't want to forget about this one. 

As part of getting descriptive summaries about the number of participants I currently have available in a subsetted dataframe I run:

Example:
```R
# D is a 100 row dataframe with columns a,b,c
# a has 100 values
# b has 87 values, rest are miissing
# c has 1 value, rest are missing
ds.subset(x = 'D', subset = 'D2', cols = c('a','b'), completeCases = TRUE)
```

I would expect `D2` to have 87 rows because row b is the limiting column with 87 values. 

however 
```R
ds.length('D2$a')
# returns
1
```

The complete cases directive was run on dataframe 'D' and then subsetted into columns `a` and `b`, hence the only rows with complete cases on 'D' was 1 row due to column `c`. 

This is verified in the serverside function https://github.com/datashield/dsBase/blob/master/R/subsetDS.R lines 48-58 where the `completeCases` parameter is handled to take complete cases of the dataframe that is to be subsetted into columns.

This is a problem we often work with large 'D' dataframes with many columns that have varying amounts of missing values, if the completeCases parameter always shortens the dataframe to 'least defined variable' we could miss out on a lot of information when we perform analyses with the subset. This is particularly apparent when we are working with variables whose harmonisations have not been finalised or have very few values by design. 

I suggest either changing the few lines to make the subset occur before the complete casing, or changing the documentation of the ds.subset function so that this is clear. Should I make a pull request for this? 

Cheers, 
Paul

**Comment by pb51** [comment]
This function is now deprecated by ds.dataFrame.subset and ds.subset should be removed. This has been discussed and agreed with Stuart (for reasons unrelated to this post). Olly how should we now deal with this - can post be closed and if so by whom?
