### ISSUE TITLE
lines #65-#80 in glmSLMADS1 are not needed and cause errors in v6.0

### ISSUE THREAD

**Issue by tombisho** [datashield/dsBase#44]
in glmSLMADS1 we have the lines:

````
#Remember model.variables and then varnames INCLUDE BOTH yvect AND linear predictor components 
	model.variables <- unlist(strsplit(formulatext, split="|", fixed=TRUE))
 
	 varnames <- c()
	  for(i in 1:length(model.variables)){
	    elt <- unlist(strsplit(model.variables[i], split="$", fixed=TRUE))
	    if(length(elt) > 1){
	      assign(elt[length(elt)], eval(parse(text=model.variables[i])))
	      originalFormula <- gsub(model.variables[i], elt[length(elt)], originalFormula, fixed=TRUE)
	      varnames <- append(varnames, elt[length(elt)])
	    }else{
	      varnames <- append(varnames, elt)
	    }
	  }

	varnames <- unique(varnames) 
````

the variables `varnames` and `originalFormula` are not used in the rest of the function. Furthermore, the `eval(parse` expression throws an error under v6.0-dev using DSLite because it asks for objects from the D dataframe in the `parent.frame`. However, seeing as the whole code block is not used I propose removing it.

**Comment by StuartWheater** [comment]
It appears to me that these changes have been made, and the mentioned code left commented out.
I am therefore closing this issue, reopen if you think this is the incorrect action.
