### ISSUE TITLE
subsetDS

### ISSUE THREAD

**Issue by tombisho** [datashield/dsBase#5]
I think an additional check is needed in subsetDS. At the moment we check that if subset by rows is used, the resulting subset should contain more than say 5 rows. However, we should probably also use the 5 value to enforce that we remove more than 5 rows. Otherwise if you take the mean, and then remove 1 row and retake the mean, you can work out individual values.

**Comment by davraam** [comment]
> I think an additional check is needed in subsetDS. At the moment we check that if subset by rows is used, the resulting subset should contain more than say 5 rows. However, we should probably also use the 5 value to enforce that we remove more than 5 rows. Otherwise if you take the mean, and then remove 1 row and retake the mean, you can work out individual values.

Hi Tom. You are right. This additional check was added in the new dataFrameSubsetDS1.o function. I think in the new release of DataSHIELD we will completly replace the ds.subset function by the ds.dataFrameSubset.o

**Comment by tombisho** [comment]
Ah OK sorry I missed that one. Great news that this is already addressed!
